In [1]:
import numpy
import os


In [2]:
file_location = os.path.join('water.xyz')
print(file_location)

water.xyz


In [3]:
help(numpy.genfromtxt)


Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [4]:
xyz_file = numpy.genfromtxt(fname=file_location, dtype ='unicode', skip_header = 2)

In [5]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [6]:
symboles = xyz_file[:,0]
print(symboles)

['O' 'H1' 'H2']


In [7]:
coordinates = xyz_file[:,1:] .astype(float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [8]:
num_atoms = len(symboles)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        x_distances = coordinates[num1,0]- coordinates[num2,0]
        y_distances = coordinates[num1,1]- coordinates[num2,1]
        z_distances = coordinates[num1,2]- coordinates[num2,2]
        distances = numpy.sqrt(x_distances**2 +y_distances**2 +z_distances**2)
        print(F'{symboles[num1]} to {symboles[num2]} : {distances:.3f}')

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


In [30]:
# i am going to modify my code to print atoms that are bonded.
# My rule will be to distance must be less than 1.5 to be considered a bond
num_atoms = len(symboles)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        x_distances = coordinates[num1,0]- coordinates[num2,0]
        y_distances = coordinates[num1,1]- coordinates[num2,1]
        z_distances = coordinates[num1,2]- coordinates[num2,2]
        distances = numpy.sqrt(x_distances**2 +y_distances**2 +z_distances**2)
        if distances > 0 and distances < 1.5:
            print(F'{symboles[num1]} to {symboles[num2]} : {distances:.3f}')


O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H2 to O : 0.969


In [31]:
# if i have measured atom 1 and 2, i don't need to do 2 and 1.
# if i have to measure atom 2 and 3, i ndon't need to do 3 and 2.
#for num2 in range(num1+num2, num_atoms):
num_atoms = len(symboles)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
         if num1<num2:
            x_distances = coordinates[num1,0]- coordinates[num2,0]
            y_distances = coordinates[num1,1]- coordinates[num2,1]
            z_distances = coordinates[num1,2]- coordinates[num2,2]
            distances = numpy.sqrt(x_distances**2 +y_distances**2 +z_distances**2)
            if distances > 0 and distances < 1.5:
                print(F'{symboles[num1]} to {symboles[num2]} : {distances:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [38]:
#reusable code : when we copy paste a part of code again and again, then you define a function.

# def function_name(parameters):

# code that you want to use
# return value_to_return

def calculate_distances(coords1, coords2):
    x_distances = coords1[0] - coords2[0]
    y_distances = coords1[1] - coords2[1]
    z_distances = coords1[2] - coords2[2]
    distances = numpy.sqrt(x_distances**2 +y_distances**2 +z_distances**2)
    return distances

In [39]:
calculate_distances([0,0,0], [0,0,1])

1.0

In [41]:
# assert statements will return True or false with an error.
# assert np.

In [44]:
#calculate_distances([0,0,0], [0,0,1])

atom1 = [0,0,0]
atom2 = [0,0,2]
calculate_distances(atom1, atom2)

2.0

In [46]:
num_atoms = len(symboles)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
         if num1<num2:
                distances = calculate_distances(coordinates[num1], coordinates[num2])
                if distances > 0 and distances < 1.5:
                    print(F'{symboles[num1]} to {symboles[num2]} : {distances:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [50]:
def bond_check(bond_length):
    if bond_length > 0 and bond_length < 1.5:
        return True
    else:
        return False

In [51]:
bond_check(1.4)

True

In [55]:
# modifyiong bond check function
def bond_check(bond_length, min_length,max_length):
    if bond_length > min_length and bond_length < max_length:
        return True
    else:
        return False

In [57]:
bond_check(1.8, 1.0, 0.5)

False

In [61]:
# In this we give deafault values to min and maximum values

def bond_check(bond_length, min_length=2.0, max_length=3.0):
    if bond_length > min_length and bond_length < max_length:
        return True
    else:
        return False

In [64]:
bond_check(2.30)

True

In [65]:
bond_check(6.0)

False

In [67]:
bond_check(5.0, 6.0, 8.0)

False

In [69]:
# In this we give deafault values to min and maximum values

def bond_check(bond_length, min_length=2.0, max_length=3.0):
    """
    This checks a bons distance to check if fills the creteria for a bond based on a minimum and maximum length.
    The deauflt minumum is 2.0 angr. and maximum is 3.0 angr.
    """
    if bond_length > min_length and bond_length < max_length:
        return True
    else:
        return False

In [70]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(bond_length, min_length=2.0, max_length=3.0)
    This checks a bons distance to check if fills the creteria for a bond based on a minimum and maximum length.
    The deauflt minumum is 2.0 angr. and maximum is 3.0 angr.

